before_script:
  - printf "FROM python:3.5-onbuild\nRUN pip install -e .\n" > Dockerfile
  - docker build -t marge-test-runner .
  - echo 'docker run --rm marge-test-runner "$@"' > docker_run
  - chmod +x docker_run

UnitTests:
  script:
    - ./docker_run pytest --cov=marge

PyLint:
  script:
    - ./docker_run pylint marge || [[ $? = 8 ]]  # ignore refactoring warnings
